version: '3'

volumes:
  postgres_data:
  redis_data:

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data