databases:
  - name: pollster-postgresql
    databaseName: pollster
    user: pollster

services:
  - type: web
    name: pollster
    env: ruby
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pollster-postgresql
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: pollster-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: redis
    name: pollster-redis
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: pollster-worker
    env: ruby
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: pollster-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
